# Generated by Django 4.0.5 on 2022-06-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.TextField(verbose_name='Ciudad')),
                ('pais', models.TextField(verbose_name='Pais')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('id_tributaria', models.TextField(verbose_name='Número de identificación tributaria')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('web_site', models.URLField(verbose_name='Sitio web')),
                ('servicio_proporciona', models.TextField(verbose_name='Servicio que proporciona')),
                ('representante', models.TextField()),
                ('cargo', models.TextField(verbose_name='')),
                ('email_representante', models.EmailField(max_length=254)),
                ('tlf', models.TextField(verbose_name='Teléfono del proveedor')),
                ('tlf_representate', models.TextField(verbose_name='Teléfono celular del representante')),
                ('tlf_local', models.TextField(verbose_name='Teléfono local')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresa.empresa', verbose_name='Proveedores')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
